# _config.yml

url: "https://gideontechok.github.io"           # Your GitHub Pages URL
baseurl: "/Trident-Professional-Services"       # Adjust if your site is served from a subpath

theme: midnight

plugins:
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
