# _config.yml
baseurl: "https://gideontechok.github.io" # Adjust if your site is served from a subpath
url: "/Trident-Professional-Services" # Your GitHub Pages URL

theme: minima

plugins:
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock

