# _config.yml

title: "Trident Professional Services"
description: "Welcome to The Ideas Forge, where technology meets creativity to shape solutions that drive progress. Whether it’s building business apps with the Microsoft Power Platform, architecting collaborative environments with SharePoint Development, harnessing the flexibility of JAMstack, or unlocking the limitless possibilities of Azure, this blog is your go-to destination for inspiration and expertise. Here, we forge ideas into powerful, transformative tools to empower organizations, developers, and business users alike."
baseurl: "" # Adjust if your site is served from a subpath
url: "https://github.com/GideonTechOK/Trident-Professional-Services/" # Your GitHub Pages URL

theme: minima

plugins:
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock

# Optional settings
markdown: CommonMarkGhPages
