name: Convert Markdown to HTML

on:
  push:
    branches:
      - main # Run on pushes to the main branch

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Pandoc
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      # Step 3: Convert Markdown to HTML
      - name: Convert Markdown to HTML
        run: |
          mkdir -p html
          for file in posts/*.md; do
            pandoc "$file" -o "html/$(basename "${file%.md}.html")"
          done

      # Step 4: Upload converted HTML files as artifacts
      - name: Upload HTML Files
        uses: actions/upload-artifact@v3
        with:
          name: converted-html
          path: html
