name: Update README with Blog Posts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate README
        run: |
          # Define the marker for the Blog Posts section
          start_marker="## Blog Posts"

          # Initialize variables
          content_before=""
          content_after=""
          in_blog_section=0

          # Read the existing README if it exists
          if [ -f README.md ]; then
            while IFS= read -r line || [ -n "$line" ]; do
              if [ "$in_blog_section" -eq 0 ]; then
                if [ "$line" = "$start_marker" ]; then
                  in_blog_section=1  # Start of Blog Posts section
                else
                  content_before="${content_before}${line}"$'\n'
                fi
              elif [ "$in_blog_section" -eq 1 ]; then
                # Look for the next heading of the same level or higher
                if [[ "$line" =~ ^##\  ]] && [ "$line" != "$start_marker" ]; then
                  in_blog_section=2  # End of Blog Posts section
                  content_after="${content_after}${line}"$'\n'
                else
                  # Skip lines within the Blog Posts section
                  continue
                fi
              else
                content_after="${content_after}${line}"$'\n'
              fi
            done < README.md
          else
            content_before=""
            content_after=""
          fi

          # Generate the new Blog Posts section
          new_blog_posts=""
          declare -A seen_files
          post_found=false

          # Only look into the 'posts' directory
          dir="posts"
          if [ -d "$dir" ] && [ "$(ls -A $dir/*.md 2>/dev/null)" ]; then
            for file in $dir/*.md; do
              file_key=$(basename "$file")
              if [[ -z "${seen_files[$file_key]}" ]]; then
                seen_files["$file_key"]=1
                title=$(grep -m 1 '^# ' "$file" | sed 's/# //')
                new_blog_posts="${new_blog_posts}- [${title:-$(basename "$file" .md)}]($file)"$'\n'
                post_found=true
              fi
            done
          fi

          if [ "$post_found" = false ]; then
            new_blog_posts="No posts found."$'\n'
          fi

          # Combine the preserved content with the updated Blog Posts section
          {
            echo "${content_before%$'\n'}"
            echo "$start_marker"
            echo "$new_blog_posts"
            if [ -n "$content_after" ]; then
              echo "${content_after%$'\n'}"
            fi
          } > README.md

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Update README with latest blog posts" || echo "No changes to commit"
          git push origin HEAD:main
