name: Update README with Blog Posts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate README
        run: |
          # Define the start and end markers
          start_marker="<!-- BLOG-POSTS:START -->"
          end_marker="<!-- BLOG-POSTS:END -->"

          # Read the existing README.md
          readme_content=$(cat README.md)

          # Extract content before and after the markers
          content_before=$(echo "$readme_content" | sed -n "/$start_marker/ q; p")
          content_after=$(echo "$readme_content" | sed -n "1,/$end_marker/ d; p")

          # Generate the new Blog Posts section
          new_blog_posts=""
          declare -A seen_files
          post_found=false

          # Only look into the 'posts' directory
          dir="posts"
          if [ -d "$dir" ] && ls "$dir"/*.md > /dev/null 2>&1; then
            for file in "$dir"/*.md; do
              file_key=$(basename "$file")
              if [[ -z "${seen_files[$file_key]}" ]]; then
                seen_files["$file_key"]=1
                title=$(grep -m 1 '^# ' "$file" | sed 's/# //')
                new_blog_posts="${new_blog_posts}- [${title:-$(basename "$file" .md)}]($file)"$'\n'
                post_found=true
              fi
            done
          fi

          if [ "$post_found" = false ]; then
            new_blog_posts="No posts found."$'\n'
          fi

          # Reconstruct the README.md with the updated Blog Posts section
          {
            echo "$content_before"
            echo "$start_marker"
            echo "$new_blog_posts"
            echo "$end_marker"
            echo "$content_after"
          } > README.md

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Update README with latest blog posts" || echo "No changes to commit"
          git push origin HEAD:main
