name: Update README with Blog Posts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate README
        run: |
          # Define markers for the blog posts section
          blog_start_marker="<!-- BLOG-POSTS:START -->"
          blog_end_marker="<!-- BLOG-POSTS:END -->"

          # Read the existing README.md
          if [ -f README.md ]; then
            readme_content=$(cat README.md)
          else
            echo "README.md not found!"
            exit 1
          fi

          # Extract content before and after the blog posts markers
          content_before_blog=$(echo "$readme_content" | sed -n "/$blog_start_marker/ q; p")
          content_after_blog=$(echo "$readme_content" | sed -n "1,/$blog_end_marker/ d; p")

          # Generate the new Blog Posts section, avoiding duplicates
          new_blog_posts=""
          dir="posts"
          if [ -d "$dir" ]; then
            for file in "$dir"/*.md; do
              if [ -f "$file" ]; then
                # Skip Info.md in the blog posts list
                if [ "$(basename "$file")" = "Info.md" ]; then
                  continue
                fi
                title=$(grep -m 1 '^# ' "$file" | sed 's/# //')
                link=$(basename "$file")
                # Avoid duplicate entries
                if ! echo "$new_blog_posts" | grep -q "(${link})"; then
                  new_blog_posts="${new_blog_posts}- [${title:-$(basename "$file" .md)}](posts/${link})"$'\n'
                fi
              fi
            done
          fi

          # Fallback for empty posts
          if [ -z "$new_blog_posts" ]; then
            new_blog_posts="No posts available."$'\n'
          fi

          # Reconstruct the README.md with updated content
          {
            echo "$content_before_blog"
            echo "$blog_start_marker"
            echo "$new_blog_posts"
            echo "$blog_end_marker"
            echo "$content_after_blog"
          } > README.md

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git

          # Commit changes only if there are updates
          if ! git diff --quiet; then
            git add README.md
            git commit -m "Update README with latest blog posts"
            git push origin HEAD:main
          else
            echo "No changes to commit."
