name: Update README with Blog Posts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Directory Content
        run: |
          echo "Root directory:"
          ls -l
          echo "'_posts' directory (if exists):"
          ls -l _posts || echo "No _posts directory found"
          echo "'posts' directory (if exists):"
          ls -l posts || echo "No posts directory found"

      - name: Generate README
        run: |
          echo "# Microsoft Power Platform Blog" > README.md
          echo "### Unleashing Innovation Through Low-Code Solutions\n" >> README.md
          echo "In a world where agility and innovation drive success, the Microsoft Power Platform stands as a game-changer for organizations looking to empower their teams with low-code solutions. Whether you're a seasoned developer or a business user with no coding experience, Power Platform has the tools to transform your ideas into impactful solutions.\n" >> README.md
          
          echo "## Blog Posts\n" >> README.md
          
          post_found=false

          for dir in posts _posts; do
            if [ -d "$dir" ] && [ "$(ls -A $dir/*.md 2>/dev/null)" ]; then
              for file in $dir/*.md; do
                title=$(grep -m 1 '^# ' "$file" | sed 's/# //')
                last_modified=$(git log -1 --format=%ci -- "$file" | cut -d' ' -f1)
                echo "- [${title:-$(basename "$file" .md)}]($file) (Last updated: $last_modified)" >> README.md
                post_found=true
              done
            fi
          done

          if [ "$post_found" = false ]; then
            echo "No posts found.\n" >> README.md
          fi

          echo "\n---" >> README.md
          echo "_Last updated: $(date)_\n" >> README.md

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Update README with latest posts" || echo "No changes to commit"
          git push origin HEAD:main
