name: Update README with Blog Posts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate README
        run: |
          # Define the marker for the Blog Posts section
          start_marker="## Blog Posts"

          # Read the existing README if it exists
          if [ -f README.md ]; then
            content_before=$(sed -n "/^${start_marker}$/q;p" README.md)
          else
            content_before="## Blog Posts"
          fi

          # Generate the new Blog Posts section
          echo "${start_marker}" > new_blog_posts.md
          declare -A seen_files
          post_found=false

          for dir in posts _posts; do
            if [ -d "$dir" ] && [ "$(ls -A $dir/*.md 2>/dev/null)" ]; then
              for file in $dir/*.md; do
                file_key=$(basename "$file")
                if [[ -z "${seen_files[$file_key]}" ]]; then
                  seen_files["$file_key"]=1
                  title=$(grep -m 1 '^# ' "$file" | sed 's/# //')
                  echo "- [${title:-$(basename "$file" .md)}]($file)" >> new_blog_posts.md
                  post_found=true
                fi
              done
            fi
          done

          if [ "$post_found" = false ]; then
            echo "No posts found." >> new_blog_posts.md
          fi

          # Combine the preserved content with the updated Blog Posts section
          {
            echo "$content_before"
            cat new_blog_posts.md
          } > README.md

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Update README with latest blog posts" || echo "No changes to commit"
          git push origin HEAD:main
