name: Update Blog with Posts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Blog
        run: |
          # Define the output file
          output_file="blog.md"

          # Create a new blog.md file and wipe existing content
          echo "# Blog Posts" > "$output_file"
          echo >> "$output_file" # Add an empty line

          # Generate the Blog Posts section
          dir="posts"
          if [ -d "$dir" ]; then
            for file in "$dir"/*.md; do
              if [ -f "$file" ]; then
                # Skip Info.md in the blog posts list
                if [ "$(basename "$file")" = "Info.md" ]; then
                  continue
                fi
                title=$(grep -m 1 '^# ' "$file" | sed 's/# //')
                link=$(basename "$file")
                # Add post to blog.md
                echo "- [${title:-$(basename "$file" .md)}](posts/${link})" >> "$output_file"
              fi
            done
          else
            echo "No posts directory found. Creating an empty blog." >> "$output_file"
          fi

          # Add a fallback message if no posts are available
          if [ ! "$(ls -A $dir/*.md 2>/dev/null | grep -v 'Info.md')" ]; then
            echo "No blog posts available at this time." >> "$output_file"
          fi

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/GideonTechOK/Trident-Professional-Services.git

          # Commit changes only if there are updates
          if ! git diff --quiet; then
            git add blog.md
            git commit -m "Wipe and recreate blog.md with latest blog posts"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
