Here's the updated workflow with the changes to handle missing files gracefully and use the `_posts/` directory:

```yaml
name: Update README with Blog Posts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate README
        run: |
          echo "# My Blog" > README.md
          echo "\n## Posts\n" >> README.md
          if [ -d "_posts" ] && [ "$(ls -A _posts/*.md 2>/dev/null)" ]; then
            for file in _posts/*.md; do
              title=$(grep -m 1 '^# ' "$file" | sed 's/# //')
              last_modified=$(date -r "$file" +"%Y-%m-%d")
              echo "- [${title:-$(basename "$file" .md)}]($file) (Last updated: $last_modified)" >> README.md
            done
          else
            echo "No posts found." >> README.md
          fi
          echo "\n_Last updated: $(date)_\n" >> README.md

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Update README with latest posts" || echo "No changes to commit"
          git push origin HEAD:main
```

### Updates Made:
1. **Check for `_posts` Directory and Files**:
   - `if [ -d "_posts" ] && [ "$(ls -A _posts/*.md 2>/dev/null)" ]; then` ensures that the `_posts` directory exists and contains markdown files.

2. **Fallback Message**:
   - If no markdown files are found, the script appends `No posts found.` to the README instead of failing.

3. **Updated Directory Path**:
   - Changed `posts/*.md` to `_posts/*.md` to match your directory structure.

This workflow will now run without errors even if no markdown files are present in the `_posts/` directory.
